<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "    <head>\n";
echo "        <meta charset=\"UTF-8\">\n";
echo "        <style>\n";
echo "            input[type=text], select {\n";
echo "                width: 100%;\n";
echo "                padding: 12px 20px;\n";
echo "                margin: 8px 0;\n";
echo "                display: inline-block;\n";
echo "                border: 1px solid #ccc;\n";
echo "                border-radius: 4px;\n";
echo "                box-sizing: border-box;\n";
echo "            }\n";
echo "\n";
echo "            input[type=submit] {\n";
echo "                width: 100%;\n";
echo "                background-color: mediumslateblue;\n";
echo "                color: white;\n";
echo "                padding: 14px 20px;\n";
echo "                margin: 8px 0;\n";
echo "                border: none;\n";
echo "                border-radius: 4px;\n";
echo "                cursor: pointer;\n";
echo "            }\n";
echo "\n";
echo "            input[type=submit]:hover {\n";
echo "                background-color: #45a049;\n";
echo "            }\n";
echo "\n";
echo "            div {\n";
echo "                border-radius: 5px;\n";
echo "                background-color: #f2f2f2;\n";
echo "                padding: 20px;\n";
echo "            }\n";
echo "        </style>\n";
echo "    </head>\n";
echo "    <body>\n";
echo         '<h1><span style="color:purple">Money Transfer Blockchain Web App</span></h1>';
echo "        <div>\n";
echo "            <form action=\"add_block.php\" method=\"post\">\n";
echo "                <label for=\"sender\">Sender:</label>\n";
echo "                <input type=\"text\" id=\"sender\" name=\"sender\" placeholder=\"Write here...\" required>\n";
echo "                <label for=\"receiver\">Receiver:</label>\n";
echo "                <input type=\"text\" id=\"receiver\" name=\"receiver\" placeholder=\"Write here...\" required>\n";
echo "                <label for=\"amount\">Amount:</label>\n";
echo "                <input type=\"text\" id=\"amount\" name=\"amount\" placeholder=\"Write here...\" required>\n";
echo "                <input type=\"submit\" value=\"Submit\">\n";
echo "            </form>\n";
echo "        </div>\n";
echo "    </body>\n";
echo "</html>\n";
?>
